// Do not edit this file!
// This file has been automatically generated by ADF.
// 
package component;

import oracle.adfinternal.view.faces.taglib.region.RichDeclarativeComponentTag;
import oracle.adf.view.rich.component.rich.fragment.RichDeclarativeComponent;
import org.apache.myfaces.trinidad.bean.FacesBean;
import org.apache.myfaces.trinidad.bean.PropertyKey;
import javax.el.ValueExpression;
import javax.servlet.jsp.JspException;

public class CustomerPanelTag extends RichDeclarativeComponentTag {

  public CustomerPanelTag() {
  }

  protected String getViewId() {
    return "/customerPanel.jspx";
  }

  protected RichDeclarativeComponent createComponent() {
    return new CustomerPanelComponent();
  }

  public void setCustFirstName(ValueExpression CustFirstName) {
    this._CustFirstName = CustFirstName;
  }

  public void setCustLastName(ValueExpression CustLastName) {
    this._CustLastName = CustLastName;
  }

  public void setCustEmail(ValueExpression CustEmail) {
    this._CustEmail = CustEmail;
  }


  protected void setProperties(FacesBean bean) {
    super.setProperties(bean);
    if (_CustFirstName != null)
      bean.setValueExpression(_CUSTFIRSTNAME_KEY, _CustFirstName);
    if (_CustLastName != null)
      bean.setValueExpression(_CUSTLASTNAME_KEY, _CustLastName);
    if (_CustEmail != null)
      bean.setValueExpression(_CUSTEMAIL_KEY, _CustEmail);
  }

  public void release() {
    super.release();
    _CustFirstName = null;
    _CustLastName = null;
    _CustEmail = null;
  }

  private ValueExpression _CustFirstName;
  private ValueExpression _CustLastName;
  private ValueExpression _CustEmail;

  private static final PropertyKey _CUSTFIRSTNAME_KEY = PropertyKey.createPropertyKey("CustFirstName");
  private static final PropertyKey _CUSTLASTNAME_KEY = PropertyKey.createPropertyKey("CustLastName");
  private static final PropertyKey _CUSTEMAIL_KEY = PropertyKey.createPropertyKey("CustEmail");

}
