// Do not edit this file!
// This file has been automatically generated by ADF.
// 
package component;

import oracle.adf.view.rich.component.rich.fragment.RichDeclarativeComponent;
import org.apache.myfaces.trinidad.context.RequestContext;
import javax.faces.context.FacesContext;
import javax.el.MethodExpression;

public class CustomerPanelComponent extends RichDeclarativeComponent {

  public CustomerPanelComponent() {
  }

  public String getCustFirstName() {
    return (String) getAttributes().get("CustFirstName");
  }

  public String getCustLastName() {
    return (String) getAttributes().get("CustLastName");
  }

  public String getCustEmail() {
    return (String) getAttributes().get("CustEmail");
  }



}
